[general]
import = ["~/.config/alacritty/theme.toml"]

[window]
padding = { x = 8, y = 8 }

[font]
normal = { family = "Hack Nerd Font Mono", style = "Regular" }
size = 12

[cursor]
style = { shape = "Beam" }

