[colors]
cursor = { text = "#1f1c27", cursor = "#a060ff" }

[colors.primary]
background = "#1f1c27"
foreground = "#a060ff"

[colors.normal]
black = "#1f1c27"
red = "#e542c0"
green = "#2dcc72"
yellow = "#d8b76e"
blue = "#9048ff"
magenta = "#dd8d40"
cyan = "#d070f0"
white = "#b6a0ff"

[colors.bright]
black = "#353146"
red = "#e542c0"
green = "#2dcc72"
yellow = "#d8b76e"
blue = "#9048ff"
magenta = "#dd8d40"
cyan = "#d070f0"
white = "#e9e4ff"
