[colors]
cursor = { text = "#000000", cursor = "#ffffff" }

[colors.primary]
background = "#000000"
foreground = "#ffffff"

[colors.normal]
black = "#000000"
red = "#b9466e"
green = "#9f6081"
# yellow = "#9f6076"
yellow = "#AD8B85"
blue = "#7a609f"
magenta = "#84609f"
cyan = "#84609f"
white = "#ddddee"

[colors.bright]
black = "#000000"
red = "#c0597d"
green = "#a9708d"
# yellow = "#a97084"
yellow = "#C2A8A3"
blue = "#8770a9"
magenta = "#9070a9"
cyan = "#9070a9"
white = "#eeeeff"
