background {
    monitor =
    path = screenshot
    color = rgba(25, 20, 20, 1.0)
    blur_passes = 5
}

input-field {
    monitor =
    size = 20%, 5%
    outline_thickness = 3
    inner_color = rgba(0, 0, 0, 0.0) # no fill

    outer_color = rgba(b6a0ffff)
    check_color=rgba(a060ffff)
    fail_color=rgba(e542c0ff)

    font_color = rgba(b6a0ffff)
    fade_on_empty = false
    rounding = 15

    position = 0, -20
    halign = center
    valign = center
	placeholder_text = 
}
