#!/bin/bash

selection=""

for f in $(ls $HOME/.config/hypr/themes/); do
	selection="$selection$f\n"
done

selected=$(echo -e $selection | rofi -dmenu -p "Theme:")

~/.config/hypr/hypr_theme.sh $selected
